{% set version = "2.3.1" %}

package:
  name: indexclient
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/indexclient/indexclient-{{ version }}.tar.gz
  sha256: 0beaf865aab58112961092aa58d06e31ca1cc8da26e9cd5cf84430d2f6567a0d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - requests

test:
  imports:
    - indexclient
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uc-cdis/indexclient
  summary: Prototype index service client.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
