schema_version: 1

context:
  python_min: "3.13"
  version: "6.2.2"

package:
  name: indexclient
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/i/indexclient/indexclient-${{ version }}.tar.gz
  sha256: 41a1545e3229df6b7ef2a95555c173691423864e0f35310f02e61a623cca62b6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python =${{ python_min }}
    - setuptools
    - poetry-core
  run:
    - python >=${{ python_min }}
    - requests

tests:
  - python:
      imports:
        - indexclient
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  summary: Prototype index service client.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/uc-cdis/indexclient

extra:
  recipe-maintainers:
    - danielnachun
